DEPARTAMENTOS = {
    "AMAZONAS CO": "AMAZONAS",
    "NORTE DE SANTANDER CO": "NORTE DE SANTANDER",
    "SANTANDER CO": "SANTANDER",
    "DEPARTAMENTO DE CÓRDOBA": "CÓRDOBA",
}

CIUDADES = {
    "BOGOTA": "BOGOTA D.C.",
    "BOGOTÁ": "BOGOTA D.C.",
    "BOGOTÁ D.C.": "BOGOTA D.C.",
}